### ISSUE TITLE
Statistics about 3 pcap files

### ISSUE THREAD

**Issue by aziel12** [activecm/threat-hunting-labs#2]
Hello, are these 3 pcap files (sample-200-500-1500.pcap) somehow labeled or related to somekind of attacks? Where can I find some more statistics about these three, I would like to use them as dataset. Thanks

**Comment by ethack** [comment]
The sample files are all the same, just with different snap lengths set. They contain a dnscat backdoor. There's no labeling other than what you can glean through the exercises. The RITA DNS and Beacons sections are probably the best summary of the malware in the pcap. 
- https://activecm.github.io/threat-hunting-labs/dns/#rita
- https://activecm.github.io/threat-hunting-labs/beacons/#rita
